#!/bin/sh
set -eu
checksum=node_modules/.npm
npm() {
  docker run \
    --interactive \
    --tty \
    --rm \
    --user node \
    --volume $PWD:/mnt \
    --workdir /mnt \
    node:8.16.0-alpine \
    npm "$@"
}

if [ ! -e "$checksum" ] || ! shasum -a1 --status -c "$checksum" ; then
  mkdir -p node_modules
  npm prune &&
    npm install &&
    shasum -a1 package.json npm-shrinkwrap.json > "$checksum"
fi
